name: flutter_ignite
description: "A flutter boilerplate project consisting of StorageManager, ThemeManager, LogManager"
version: 0.2.7
homepage: "https://github.com/tanvoid0/flutter_ignite"

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ansicolor: ^2.0.3
  archive: ^4.0.2
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.4
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  package_info_plus: ^8.2.1
  process_run: ^1.2.2+1
  responsive_framework: ^1.5.1
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  flutter_lints: ^5.0.0

flutter:
